### ISSUE TITLE
Tags Not Updating Properly

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#1]
A big frustration is the tags in Door43 are not updating the indexes properly.  We are using the https://www.dokuwiki.org/plugin:tag plugin.

When generating reports they are not always up to date and often never reach consistency.  We either need to re-implement how the reports are generated or fix the indexing issue.

An example report page is https://door43.org/en/bible/admin-reports/notes-team-admin/mat.

**Comment by jag3773** [comment]
Here is another report that doesn't always work correctly: https://door43.org/en/bible/admin-reports/check-tags.

This plugin is also related: https://www.dokuwiki.org/plugin:searchindex .

One idea I've had is to write a new plugin that does a full text search through the related namespace (possibly forking to grep).  This would ensure that the reports are always 100% consistent and it's not likely that the added time to do the search would be an issue.

**Comment by superdav42** [comment]
Been looking at this and it it look like other people have experienced this with dokuwiki as well. If the only issue is the search index not being able to keep it up we could add a cron job to generate the search index which would probably keep it more up to date then the webbug method that dokuwiki uses now. 

Alternately we could install [sphinx](http://sphinxsearch.com/) and the [sphinx search plugin](https://www.dokuwiki.org/plugin:sphinxsearch)

It appears that search has been the weakest part of dokuwiki as far as scalability is concerned.  
 https://www.dokuwiki.org/devel:scalability

Do we have the ability to setup cron jobs now?

Can we get sphinx installed?

**Comment by superdav42** [comment]
Noticed there really isn't much of a problem with:
https://door43.org/en/bible/admin-reports/check-tags
It's search for content like `{{tag>publish` but the items it finds with problems have the content like `{{tag> publish}}` the space after the '>' is causing it to be flagged as not tagged when it really is and the tag plugin reads it find. It's using the pagequery plugin to generate that report and it doesn't really know anything about tags, it just searches the page content. If we update all those pages to remove the space it'll fix that problem.

**Comment by superdav42** [comment]
@jag3773 Updated enhancedindexer plugin to prevent the default indexing action from happening on every page view. This means we won't need to make changes to core code. Please update the plugin on prod then run: 
`php -d memory_limit=512M lib/plugins/enhancedindexer/bin/indexer.php -n en`
on prod until it only says up to date for each item.
I had to run it a few times on the test server before it would do this, haven't figured out why exactly, it could be someone else was making changing to plugins that would invalidate the index. Enabling or disabling some plugins will invalidate the index for all content. 
Once it's running quickly we can add it to a 5 min cron. We'll also want to disable the other cron which hits all the pages.
