### ISSUE TITLE
tA Word Export

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#104]
We need a Word export of all the tA material, by Tuesday.

**Comment by jag3773** [comment]
Here are a few tweaks that need to be made to the export:
- We need a TOC based on https://pad.door43.org/p/ta-modules
- We only want to include **volume 1** pages for this document.
- We need to include Door43 pages that are linked to (e.g. statement of faith)
- Include backlinks at the end of page that takes the user back to the top of the document
- Include a licensing page at the front of the document

Also, even though I referenced a PDF, that was by accident, at this point we only need this as DOCX.

**Comment by ChrisJarka** [comment]
Pictures/graphics are not showing - see page 16 for this example: {{ :en:ta:vocabulary:we_us_inclusive.jpg?nolink&298x62 }}{{ :en:ta:vocabulary:we_us_exclusive.jpg?nolink&298x62 }}

**Comment by ChrisJarka** [comment]
Can there be a page break at the end of every module/page/slug?
Can the modules be in the same order as what is on this page? https://pad.door43.org/p/ta-modules

**Comment by ChrisJarka** [comment]
On page 10 of the docx - the formatting of what should be plain text is not. Is it because the page has a line (----) between the sections? https://door43.org/en/ta/vol1/translate/figs_hypo

**Comment by ChrisJarka** [comment]
It looks like italics are not being recognized - see pages 16 and 18 for just 2 examples.

**Comment by ChrisJarka** [comment]
Pictures are not being shown - page 15

**Comment by ChrisJarka** [comment]
Is there a way that level headings could be formatted? On the ta-modules page there are 2 levels in the list - would be nice to have that in the TOC.
Statement of faith is still not right - it's pulling the syntax - this might be a Ben Jore fix.
Same thing for the Open License (oops misspelled - now fixed in the slug)
As Jesse mentioned - italics are not showing correctly in Word
Could the pages be numbered?

**Comment by benjore** [comment]
I bypassed the transclusion issue (Statement of Faith, Translation Guidelines, Open License) by copying and pasting the content in there. That shouldn't be a problem any more.

**Comment by ChrisJarka** [comment]
Thank you Ben ☺

Blessings,
Christine
407-852-5343

**Comment by phillip-hopper** [comment]
Note to self: for images search for ".png" and "{{"

**Comment by benjore** [comment]
Title Page:
Make title: "translationAcademy Volume 1"
Add "Draft" underneath title 
Add a date stamp underneath "Draft" so we can differentiate the different versions of the document running around.

**Comment by benjore** [comment]
Fix internal links. 
I realize this is difficult since the links that end up in Door43 will be linking to web pages while the links in the document will link within the document. I have an idea that could potentially fix that. If we were to write links as [[slug|Link Text]] can a script be written so that when pushing to Door43, it links to the webpage, but when pushing to the document, it puts in an internal link? If that will work, somebody will have to go through and update all of the links (most of them are wrong anyway), but that could be slick.

**Comment by benjore** [comment]
Table of Contents: 
1. Put the license page before the TOC
2. No page break from the title, "Table of Contents", to the start of the table itself
3. Each entry needs to be numbered
4. Proper indentation
5. The sections need to be clearly separated in the TOC with headings for each section: Introduction, Translation Manual, Checking Manual, Technology Manual
6. Each entry should be a link to that page

**Comment by benjore** [comment]
Modules missing from document
1. The unfoldingWord Project - uw_intro
2. Translation Guidelines - translation_guidelines
3. Introduction to Translation Manual - translate_manual
4. Why Should we Translate the Bible - translate_why
5. What process do I follow to translate - translate_process
6. The Original and Source Languages - translate_original
7. What are Meaning Based Translations - translate_dynamic
8. Forms of 'You' - Dual-Plural - figs_youdual
9. Order of Events - figs_events
10. Parables - figs_parables
11. Level 1 Check - level1
12. Accuracy Check - accuracy_check

**Comment by benjore** [comment]
Extra space between lines of 1st and second bullets (sometimes)
e.g. p15, 17, 23, 28, 29, 39, 47, 60, 66, 112

**Comment by benjore** [comment]
Strange indentation after a list of bullets 
e.g. p34 (“Examples from the Bible” & Luke 1:3 are indented)
p35 from the heading “Accurate” on down is indented
p48 “Examples from the Bible & John 6:35
p50 “Translation Suggestions”, “Examples from the Bible” and Luke 13:34b

**Comment by benjore** [comment]
Error Message
End of page 76

**Comment by phillip-hopper** [comment]
@benjore The table of contents is out of my control - the only options I have is to have one or to not have one. I can't change the position or how it looks. If someone wants to edit the file and make it look pretty or rearrange the pages, he is free to do so.

And the entries in the TOC are already links to the page, they just don't look like it (CTRL+Click).

**Comment by ChrisJarka** [comment]
I’m dying to help – but I’m just out of time and availability. It needs to go to the proofers tomorrow, correct?
Blessings,
Christine
407-852-5343

**Comment by jag3773** [comment]
@phillip-hopper There is some good news here, rather than sending a single Word doc we'd like to send over a zip file that contains 3 folders, corresponding to the tA sections, and then one Word doc per module.  e.g.

Zip:
- Technology
  - tech mod 1.docx
  - tech mod 2.docx
  - etc.
- Translation
  - trans mod 1.docx
  - trans mod 2.docx
  - etc.
- Checking
  - checking mod 1.docx
  - checking mod 2.docx
  - etc.

Does that make sense?

This should eliminate the TOC and the page break issues.  (Note that none of the original work is lost as we still want the single file output for later on down the line)
