### ISSUE TITLE
Remove Media Manager Link from Template

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#107]
When you are logged in you see a Media Manager link in the top right by the search bar.  We do not recommend that people use this and so it would be good to remove that link entirely.  We may replace it with a link to the audio upload form when we have that ready.

**Comment by jag3773** [comment]
I think we want to replace this link with a link to the request to publish form.

**Comment by jag3773** [comment]
Put Media Manager link in the Footer.

**Comment by richmahn** [comment]
@a-gundy The Publish request URL is: http://td.unfoldingword.org/publishing/publish/request/

If we can have that in the top right where Media Manager is, that would be ideal, with something like "Publish Request" as the text. What do you think @jag3773?

Also, should we start to make some footer links? Currently no place for a secondary menu at the bottom.

**Comment by jag3773** [comment]
Yes, call it "Publish Request" or, if it fits, "Publish Request Form".

**Comment by a-gundy** [comment]
Should I put the Media Manager link in the footer? Should any other links go there?

**Comment by richmahn** [comment]
Ah, right @a-gundy , forgot about moving it to the footer. Yet does anyone actually upload Media @jag3773 using that, especially now that all images are pretty much set for OBS? We probably don't need to, in my opinion.
