### ISSUE TITLE
Remove unused plugins (Dokuwiki)

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#11]

**Comment by richmahn** [comment]
I have wondered if a lot of plugins in the list I made (again pasting it here for reference, below) if they are used, how they are used, etc. Maybe need everyone go through and note which plugins they know are useful and used?

https://docs.google.com/spreadsheets/d/1D1b7IMarrozMw40irlGOuMRlcL-SJmCjlDslKksCbxw/edit?usp=sharing
