### ISSUE TITLE
WYSIWYG Editor Notice

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#117]
The WYSIWYG editor needs to display the same notice that the DW editor displays, see #115 .

**Comment by richmahn** [comment]
This is not as easy to fix as DW editor text in #115 as the text is all generated from the ckgedit plugin which we currently pull from the third-party repo. We need to figure out if there is a way to write our own plugin to do a hook which would know it is a do=edit and that the user is using the CKG Editor and put the text at the bottom from $this->getLang('licenseok') and $license[$conf['license']].
