### ISSUE TITLE
Update plugins to latest version (Dokuwiki)

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#12]

**Comment by richmahn** [comment]
Can starting using https://docs.google.com/spreadsheets/d/1D1b7IMarrozMw40irlGOuMRlcL-SJmCjlDslKksCbxw/edit?usp=sharing to gather info on what plugins can be upgraded, what version of Dokuwiki they are compatible with, which of our own plugins need to be modified for the upgrade, etc.

**Comment by jag3773** [comment]
@richmahn can we close this?

**Comment by richmahn** [comment]
Closing...
