### ISSUE TITLE
Update door43.org to use Noto Sans fonts rather than Lato

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/Door43#120]
Need to get the font TTF files from [here](https://www.google.com/get/noto/) and use fontsquirrel.com to convert them to WOFF and WOFF2 format to use as web fonts. See unfoldingword.org as one example of how this can be implemented - https://unfoldingword.org/css/main.css

**Comment by jag3773** [comment]
Is this finished @richmahn ?

**Comment by phillip-hopper** [comment]
@jag3773: The css I used apparently on works in Firefox. I have a pull request coming soon.
