### ISSUE TITLE
Move Door43 Content Repos to gitolite3

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#127]
Currently, the Door43 Github org (https://github.com/Door43) is our distribution point for our content repos from Door43.  These all need to move into our gitolite3 installation.

Process for this will mainly be to:
1. Create hooks in gitolite3 that can notify the servers of updates coming into the repos,
2. Test,
3. Update the remote location for each of the ~7,000 repos on the us, jp, and uk servers.

Lastly, we'll need to provide zipballs for the latest version of each repo, similar to how Github does that and we'll need to update the links in the Door43 sidebar for each language to point at these.

**Comment by richmahn** [comment]
Will the zipballs be how one would check out some of the language repos on their own machine? Sorry if wrong place to ask this, but I need to understand how the access will work (if anyone will be able to download the repo or zipball) and how we want that to work on Door43 test and production as well.

**Comment by jag3773** [comment]
​Potentially, it's more for anyone else in the world that wants to grab all
the Door43 content for a given language.​

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by alerque** [comment]
If you are moving these repos off Github please, please, please keep read-only git clone access open to the world.

**Comment by jag3773** [comment]
@alerque That's the goal of providing the zipballs.

**Comment by alerque** [comment]
`zipballs !== git clone` :-(

**Comment by da1nerd** [comment]
gitolite3 is able to provide read only access to non-authenticated users as well and wouldn't require any extra setup. The zipballs would be helpful for less techie people, but we probably don't want to cut off direct git access.
