### ISSUE TITLE
Better plugin management, maybe use gittool

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#13]

**Comment by jag3773** [comment]
In progress solution is the data in this repo, thanks to @richmahn

**Comment by richmahn** [comment]
I have also made a spreadsheet so we can have a better grasp of what plugins are included in this, where they come from, etc: https://docs.google.com/spreadsheets/d/1D1b7IMarrozMw40irlGOuMRlcL-SJmCjlDslKksCbxw/edit?usp=sharing

**Comment by jag3773** [comment]
@richmahn can we close this?

**Comment by richmahn** [comment]
I'm kind of questioning how we are doing plugins, as it has been a pain to switch from branches that have submodules (repos in repos) and those that have those directories but aren't repos. Maybe once we have all repos as submodules that should be submodules in master then we won't have such a headache, but I have been waiting to close this just to see if this actually works ok with submodules.
