### ISSUE TITLE
tN Copy Plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#133]
Same as #59 but for OBS tN and Scripture tN.

**Comment by phillip-hopper** [comment]
From @jag3773:  The UI for the tN, tQ, tW copy needs to be reworked... We need to have a check box for each of those, something like

``` Include:
* translationQuestions
* translationWords
* translationNotes
```

The \* would be checkboxes

**Comment by jag3773** [comment]
Note that this is completed when it works for OBS, we'll create separate issues for Scripture.
