### ISSUE TITLE
tW export formatting: tables need to go bye bye

### ISSUE THREAD

**Issue by alerque** [unfoldingWord-dev/Door43#137]
The tW pages (at least the Bible ones) have formatting miss-match issues that make typesetting the export data a nightmare. One of the most notable problem is a whole bunch of extraneous table markup in what should be simple list structures. This is especially problematic for the PDF export because tables in TeX are not easily mapped from HTML ones and pandoc creates a giant mess. Worse it tries to use the `\package{longtable}` to smooth things over, and what ends up happening is every list item from the html that is wrapped in a bogus table ends up getting typeset inside `\begin{minipage}`. This is not easy to fix on the pandoc/LaTeX side. Even if you do fix it, longtable isn't compatible with multi-column output or other publishing packages which might be more useful. Garbage in = garbage out:

Code like this:

```
<div class="level2">
<div class="table">
<table class="ul">
        <tr>
                <td class="page"><ul><li><a href="/en/bible/notes/act/07/22" class="wikilink1" title="en:bible:notes:act:07:22">Acts 07:22-25</a></li></ul></td>
        </tr>
        <tr>
                <td class="page"><ul><li><a href="/en/bible/notes/act/07/26" class="wikilink1" title="en:bible:notes:act:07:26">Acts 07:26-28</a></li></ul></td>
        </tr>
        <tr>
                <td class="page"><ul><li><a href="/en/bible/notes/gen/16/05" class="wikilink1" title="en:bible:notes:gen:16:05">Genesis 16:5-6</a></li></ul></td>
        </tr>
</table>
</div>
```

Comes out from Pandoc like this:

```
\begin{longtable}[c]{@{}l@{}}
\toprule
\begin{minipage}[t]{0.97\columnwidth}\raggedright\strut
\begin{itemize}
\tightlist
\item
\href{}{Acts 07:22-25}
\end{itemize}
\strut\end{minipage}\tabularnewline
\begin{minipage}[t]{0.97\columnwidth}\raggedright\strut
\begin{itemize}
\tightlist
\item
\href{}{Acts 07:26-28}
\end{itemize}
\strut\end{minipage}\tabularnewline
\begin{minipage}[t]{0.97\columnwidth}\raggedright\strut
\begin{itemize}
\tightlist
\item
\href{}{Genesis 16:5-6}
\end{itemize}
\strut\end{minipage}\tabularnewline
\bottomrule
\end{longtable}
```

Which ends up like this:

![-home-caleb-projects-uw-tools-phm pdf_034](https://cloud.githubusercontent.com/assets/173595/8871258/a94dbb06-31fc-11e5-9494-1d857cd236fc.png)

Rather than post-process a huge amount of bogus nested markup so that the PDF doesn't come out with a bunch of extra space, I think it needs to be fixed at the source. As the Bible references don't actually seem to be tables, that markup needs to go away (at least in the export versions, e.g. https://door43.org/_export/xhtmlbody/en/obe/other/aaron and similar URLs). Whatever text processing needs to be done to clean this up wherever it's being generated would be much more productive than trying to post-process it out of everything.

For an example of bad formatting, view source on the Bible References for: [tW: wrong](https://door43.org/en/obe/other/wrong). By contrast [tW: aaron](https://door43.org/en/obe/other/aaron) has much simpler and normal UL/LI structures in the "Examples from Bible Stories" section that is much easier to process and typeset.

**Comment by jag3773** [comment]
This is likely a result of copying and pasting from Word - or possibly just using the WYSIWYG editor.

**Comment by alerque** [comment]
I think @richmahn cleaned up some of this markup already. I'm not sure if it was all taken care of and whether this can be closed yet or not. If this turns out to be a problem at the editor level some sort of save filter/hook like we talked about for fixing other markup should include a check for this. Tables for no good reason may look fine on the web in that moment but they will inevitably make a mess downstream in other formats.

**Comment by jag3773** [comment]
The "correct" solution here would be to fix the WYSIWYG editor to stop putting the garbage into here.

**Comment by alerque** [comment]
@jag3773 Good luck with that. WYSIWYG editors are mostly at the mercy of browsers' contentEditable and its notoriously spastic behavior. Long term there is a better way to architect the whole flow of user editable content in a way that will produce much less mess and predictable mappings between formats and that's using the newly open-sourced [ProseMirror](http://prosemirror.net/). However bringing this up as a replacement for the WYSIWYG in your wiki and working out all the right mappings so people have access to just exactly the formatting options you want on the output side will take a non-trivial amount of work.
