### ISSUE TITLE
Upgrade DokuWiki to 2014-09-29d "Hrun"

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#140]
David, can you take this on?  I'm thinking we should create a new dev branch to hold the code and work on any plugin compatibility issues that are bound to come up.  Please work with @richmahn on orchestrating this and we can plan to deploy it in late August if that's not too soon.

**Comment by richmahn** [comment]
Any plugins that are their own repository on Github should be made into submodules (git submodule add &lt;GitHub Url&gt;) and updated to the latest version that is compatible with Hrun.

NOTE: The translate plugin has been modified by @phillip-hopper, so he needs to separate changes he made into a new plugin, if possible.

**Comment by superdav42** [comment]
@richmahn this done?

**Comment by richmahn** [comment]
Right, this is more than done as I have updated it to the 2015-08 release. That is already in master ready to be pushed on production. Will close this.
