### ISSUE TITLE
Stop "external edits"

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#149]
When a script on the server edits a file in DW it shows up in the revision history as "external edit".  While this is not a problem conceptually, it causes a lot of consternation for those that don't know what it means.

The https://github.com/unfoldingWord-dev/tools/blob/master/obs/dokuwiki/convertlinks.sh script runs once a day and is the primary offender.  We have a couple options:
1. Stop running that script daily and only run it for given namespaces when people notify us of an image problem.
2. Rewrite that script to use dwpage.php (https://www.dokuwiki.org/cli), which would allow us to specify information on what exactly is being changed and alleviate concerned parties as they review the changelogs.

Option 2 would be good.  Perhaps there are other options?

Ideally, it would be nice to have a wrapper script around dwpage.php so that it is easier to use from a shell.

**Comment by alerque** [comment]
Something is "off" here architecturally. I think this is roughly analogous to to unfoldingWord-dev/tools#109 in that the mere existence of this hack downstream is a pretty good indication that it should get fixed upstream. It's great to be able to clean up data after the fact, but if you have to run something in cron to keep the repo clean then something is wrong.

So more options (there may be others, this is just brainstorming):
1. Implement (pre?) commit hooks that clean this sort of thing up on an event driven basis and only iterate over the material in the commit.
2. Implement these rules as some sort of filter that catches parsing issues in the editor itself (whether inline or at save time or whatever).

**Comment by superdav42** [comment]
I'll create a plugin that listens to IO_WIKIPAGE_WRITE event which where we can modify the data before it's saved. Definitely a much better design.

**Comment by jag3773** [comment]
Sounds good, that would be ideal for unfoldingWord-dev/tools#109 too.

**Comment by jag3773** [comment]
Also related #57 .

**Comment by jag3773** [comment]
Related to #137

**Comment by phillip-hopper** [comment]
Change "external edits" to "Door43 Server Edit"
