### ISSUE TITLE
Door43-conf Repo

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#150]
We need to figure out how to keep the 4 private files in conf/ under version control in a separate git repo.  Currently, we setup a door43-conf repo outside of the Door43 docroot and linked the files into conf/.  This does not work because when DW updates these files it seems to move them to .bak and then creates a new one with the changes.  Thus, the symlink is broke.

Once we have this ironed out then we need to:

[ ] Configure a post-receive hook in the door43-conf repo (which is in gitolite) to notify the server clusters to pull an update
[ ] Configure something on the servers to pull the changes (maybe use the webhook script? https://github.com/unfoldingWord-dev/flask-github-webhook)

**Comment by richmahn** [comment]
Will do this by:

1) adding ./conf to the .gitignore file
2) moving conf to conf.dev and add it to repo
3) updating door43_bootstrap to copy conf.dev to conf
4) On production we clone the repo for saving config files to ./conf
5) The whole ./conf directory will be backed up/pushed to the production config repo

**Comment by richmahn** [comment]
The repo in #1 and #2 are the Door43 repo, the repo in #3 and #4 is the gitolite repo for production config files.

**Comment by alerque** [comment]
This is a great use case for [git-crypt](https://www.agwa.name/projects/git-crypt/). You could keep the config file with your super secret stuff in it in the regular repo along side all the other files, but tag it to be encrypted. The git repo itself will store the encrypted version and anybody that tries to look at it will just see random data. They won't need special tools to use the repo and everybody keeps working as normal EXCEPT the people with access to the configs. Basically your production systems and anywhere you want to admin the config has to have git-crypt installed and have access to a the right private key to decrypt it. On systems where the repo has been marked to be decrypted automatic git filters will take care of having your working copy be a decrypted file even while the repo still holds only the encrypted version.

**Comment by richmahn** [comment]
I had thought about crypting stuff, but still makes things confusing as a development environment would want readable config files there. But the on production have its own config files with sensitive information in the very same files exist in a dev environment. If a change is made Door43.org to the config file on production, we want it then pushed to the config repo. If we did this with the Door43 repo, we'd also have to know to rename it to something like local.php.prod and encrypt it, then on a mirrored site it would have to decrypt and move to local.php. Doesn't seem all that great, unless I'm missing something. Just having a whole config dir for production that isn't checked into the repo seems easier. Any other thoughts?

**Comment by jag3773** [comment]
I'd like to implement this as we discussed @richmahn, with the dedicated repo.  I'm not too crazy about publishing password files, even if they are encrypted.
