### ISSUE TITLE
Puppet Testing

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#151]
We need to setup some automated tests for the puppet repository.  For now, let's add a 'test' target to the makefile and at least do a syntax check (via `puppet --parseonly /path/init.pp`).

If we can add anything else in that would be good.

**Comment by greenpotatochip** [comment]
found a nice one liner to parse recursively. It takes a min to go through all the files, but checks everything
find -name '*.pp' | xargs -n 1 -t puppet parser validate

**Comment by alerque** [comment]
@greenpotatochip Passing the output of `find` to `xargs` is problematic, but find has built in tools to to the same thing:

```
find ./ -name '*.pp' -exec puppet parser validate {} \;
```

If puppet can handle being run from the directory where the result was found (as opposed to where you run the find command from), using `-execdir` is an even safer option. You can add `-print` before `-exec` if you want to see which file it's on as it goes through. Or if you need a custom message try:

```
find ./ -name '*.pp' -printf "Running Puppet validator on %f\n" -exec puppet parser validate {} \;
```

Note I also explicitly included `./` as the base path to search from. This is the default on Linux if you don't specify a path but on BSD systems (like OSX) it must be spelled out.

**Comment by greenpotatochip** [comment]
Thanks. I'll modify it.
