### ISSUE TITLE
Schedule Server Updates

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#160]
Let's schedule server OS updates Sunday night, the 23rd.  Please update test, preprod, jp, and uk beforehand to verify that everything is functioning, then we can update us on Sunday.

**Comment by greenpotatochip** [comment]
Is it okay to reboot if we get kernel updates?

**Comment by jag3773** [comment]
I added https://github.com/unfoldingWord-dev/Door43/wiki/Server-Updates.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by greenpotatochip** [comment]
Server updates completed 8/23/2015
We have a glitch with python and webhook service on test server.
