### ISSUE TITLE
Deploy New SSL Cert

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#162]
The new SSL cert needs to be deployed to all of the unfoldingword.org domains that are using it.  Right now, I think that is:
- api.unfoldingword.org
- unfoldingword.org
- pki.unfoldingword.org

The api site is served from us, the pki site is served from it's own vm (pass me the cert for this when it's ready and I'll deploy), the main site is served from AWS S3 and Cloudfront.

**Comment by greenpotatochip** [comment]
I uploaded it to aws
