### ISSUE TITLE
Amharic Script Font

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#185]
We need to switch to the Abyssinica SIL font for Amharic and any language that uses the Amharic script.

Please also increase the word spacing slightly, perhaps .02em .

**Comment by phillip-hopper** [comment]
@richmahn: Do you have the woff/woff2 files for this font?  I'll probably need to make the same change to unfoldingword.org, and I think I'll need both regular and bold.

This is the list of languages that are using this script:

```
// Noto Sans Ethiopic supports these languages
:lang(am),  // Amharic
:lang(gez), // Geez
:lang(ti),  // Tigrinya
:lang(tig)  // Tigre
{ font-family: NotoSansEthiopic, sans-serif; }
```

**Comment by richmahn** [comment]
This "early access" CSS file has the woff/woff2 files: http://fonts.googleapis.com/earlyaccess/notosansethiopic.css

**Comment by richmahn** [comment]
@phillip-hopper Oops, I see this was about the Abyssinica SIL font, not the Noto Sans font. Had replied thinking you had wrote that on a previous issue. Still gathering these fonts.

**Comment by richmahn** [comment]
For reference, and may have what @phillip-hopper needs too, public link from Brad:

https://www.dropbox.com/sh/q07c6c0t2bi63da/AADez239gG5hwKxv7sDwfApQa/Abyssinica?dl=0
