### ISSUE TITLE
1 Button Export

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#186]
Would be nice to have a one button export for content to come directly out of Door43.  This is not as easy as it sounds as it will be dependent on the type of resource it is, may need to include multiple sub-pages to work as expected.

**Comment by jag3773** [comment]
We have a book creator plugin enabled that seems to have potential for doing this for us.  I think what we would need to make it fully functional would be to create prepackaged lists of files to be a part of a book.  For instance,
- [ ] OBS
- [ ] OBS tN
- [ ] OBS tW
- [ ] OBS tQ
- [ ] tA

Looks like that plugin is using a cookie to define what pages are included, so a possible implementation would be to set a cookie with that predefined list of pages and then take the user to the export page.

**Comment by jag3773** [comment]
@phillip-hopper This is related to the OBS export that you put together.

Also, I'm not sure if we can re-style the exported documents with the book creator plugin, but that may be desirable.

**Comment by benjore** [comment]
I think we need to have the following downloads available: 
- OBS (this is already complete)
- OBS + tN + tW + tQ (with and without images)
- Bible + tN + tW + tQ (one download per book AND one download for everything)
- tA (there is still a lot of content being created here, so it might be a while before this can be finalized)
