### ISSUE TITLE
DFT Comparer

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#193]
This should probably be a feature to add to the comparer app that @richmahn worked on.

In order to check translations in Door43 for faithfulness in translation of Divine Familial Terms, it would be very helpful to have a simple web app that would enable a user to choose source (ULB by default) and target language.

Then, when the user clicks “Compare”, the web app would display the translations of the following verses (or the chunks in which they appear), together with the ULB for the same verses:

Luke 1:13, 31, 32, 35; 3:22, 23; 10:21, 22; 11:11, 13; 12:53.
John 3:18, 35; 4:53; 5:17-23.

We'll get a list together of the relevant OBS frames also.

**Comment by jag3773** [comment]
Known relevant OBS frames (from @benjore ):
22-04
22-05
24-08
24-09
25-02
25-04
26-09
29-09
31-08
32-06
36-05
37-05
38-12
38-15
39-03
39-04
40-05
40-07
40-08
42-10
42-11
43-08
46-06
48-13
49-01
49-03
49-09
49-12
49-14
50-10

**Comment by klappy** [comment]
Would this be considered a topical check for tC?

**Comment by benjore** [comment]
This is my list of DFT for the Bible. I sent it to @ChrisJarka so she could check it against her list. https://docs.google.com/document/d/1gWSK1v5GTHI1gIiIIErCO39HOBNu5HYZjnuOUhj1AAo/edit#

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/door43.org #645](https://github.com/unfoldingWord-dev/door43.org/issues/645) via [**ZenHub**](https://www.zenhub.com/)
