### ISSUE TITLE
Content: Sanctify KT

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#201]
The https://door43.org/en/obe/kt/sanctify page either is not an OBS kt, or it is not formatted correctly to be an OBS kt.  The section for 'Examples from the Bible stories:' is missing if it is supposed to be an OBS kt.

**Comment by ChrisJarka** [comment]
I could not find any back linked OBS pages to the sanctify page - so I removed the ktobs tag.
