### ISSUE TITLE
Remove uwadmin transclusion from sidebar

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#209]
Every language with OBS setup is currently transcluding their uwadmin page in it's sidebar.  Now that we have a plugin that is reading the API directly for this and noting it at the top of the translation, we no longer need or want this.

Note that the uwadmin pages themselves need to remain for now.

**Comment by richmahn** [comment]
I'll remove all Latest Status info from sidebar.txt for each language and then make sure the OBS setup isn't generating that transclude in the sidebar.txt.

**Comment by jag3773** [comment]
OK, @phillip-hopper did already commit fix for #229

**Comment by richmahn** [comment]
Ok, good to know. I have sed commands to remove such text from the sidebar.txt file for a language, but now to figure out best way to change hundreds of sidebar.txt files and commit/push each one.

**Comment by jag3773** [comment]
See code at
https://github.com/unfoldingWord-dev/tools/blob/master/general_tools/dokuwiki/simplescripts.sh#L121
.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
