### ISSUE TITLE
Not Published Message

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#210]
Currently, the plugin that reads the API to get checking level information outputs the following when the resource has not been published: "No checking level information found."  This message needs to be changed to:

"This resource has not yet been published to unfoldingWord.  If it is completed, please submit the request to publish form."

"request to publish" should link to http://td.unfoldingword.org/publishing/publish/request/.

**Comment by cnuts** [comment]
I would like to reproduce the current scenario so I can test after making the text change.  Can you point me the right direction?

**Comment by phillip-hopper** [comment]
@cnuts I think this file demonstrates how to do what you are asking: https://github.com/unfoldingWord-dev/Door43/blob/development/lib/plugins/door43obs/_test/CreateNow.test.php
