### ISSUE TITLE
Searching for language in the door43translation plugin not working correctly

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/Door43#215]
`Ben Jore: On the main page door43.org , the “select a language” dropdown doesn’t seem to be working properly. For instance if I search “soga” the language that is called “Soga” does not appear. I have to type in the language code “xog” for it to appear. Likewise if I start typing “Ikpeng” it doesn’t show up, I have to type in “txi”.  Likewise with "Ghotuo" and "aaa". (But if I type in “Rom” for “Romanian” (ro), it does show up…) Is it possible to have the search look for language name matches as well as language code matches?`

**Comment by jag3773** [comment]
This information has already been hashed out in unfoldingWord-dev/ts-android#493.

**Comment by jag3773** [comment]
Note that all of our search boxes (tD, tS, Door43, tK, etc.) need to operate the same way.  @richmahn please write up a short document (maybe in the Github Door43 wiki here) describing how the search should work and then let's test all of the projects to see if they are working correctly or if we need to make tweaks.

**Comment by richmahn** [comment]
Ok, will do.

**Comment by jag3773** [comment]
I need to add to this an issue when searching for `taha` or `tama`.  There is a language Tahaggart Tamahaq (thv) that only shows up when you enter `thv`.  Not when you search for it by name.

**Comment by richmahn** [comment]
Added this wiki: https://github.com/unfoldingWord-dev/Door43/wiki/Language-search-field-result-requirements

**Comment by phillip-hopper** [comment]
@jag3773 I think the `Tahaggart Tamahaq (thv)` problem is either a bug in the API or a misunderstanding of how the API works. The language selector gets a list of languages from the API based on the first 2 characters entered, so if someone typed `taha` in the search box, the API will be sent this query, `https://door43.org:9096/?q=ta` which does not return `Tahaggart Tamahaq (thv)`.  Is this a bug in the API, or am I misunderstanding how it works?
