### ISSUE TITLE
Resources Feedback Form

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#225]
We need to create a simple form that allows people to submit feedback on our various resources.

The form response should send an email to our help desk (ask Jesse for the correct address).  The user's email should be in the "from" field so that they become the requester in our help desk software.

Fields on the form:
- Name (DW should prefill if logged in)
- Email (DW should prefill if logged in)
- Username (DW should prefill if logged in)
- Resource (Drop down with the following options)
  - OBS
  - OBS tN
  - OBS tQ
  - tW
  - tA
  - Bible tN
  - Bible tQ
  - ULB
  - UDB
- Location of issue (Dynamic based on resource):
  - OBS - Drop down of frame list (01-09, 40-03, etc.)
  - OBS tN - Drop down of frame list (01-09, 40-03, etc.)
  - OBS & Bible tW - Text box for tW entry name (God, Heaven, etc.)
  - OBS tQ - Drop down of story list
  - tA - Text box for module name
  - Bible (ULB/UDB) - Text box for reference
- Version of Resource (text box) (this should be optional)
- Type of Issue (Drop down with following options):
  - Typo
  - Content Error
  - Suggestion
- Seen in (Drop down with the following options):
  - Door43
  - translationStudio
  - unfoldingWord mobile app
  - unfoldingWord website
  - PDF
- Description of Issue (text area).

**Comment by jag3773** [comment]
Note that this will be similar to the contact form: https://door43.org/contact.

**Comment by benjore** [comment]
I think this would be very helpful, Jesse. I would suggest a few changes to the form. 
1. Add a username field (DW should prefill if logged in)
2. Rather than specifying OBS tW or Bible tW, just have one category for tW since all the OBS tW are also used for Bible translation as well. (We could specify phase 1 or phase 2, but we haven't even divided it out like that online yet...)
3. Add Bible tN
4. Add Bible tQ

**Comment by jag3773** [comment]
OK, @benjore I made those changes in the original post above.

**Comment by jag3773** [comment]
Possibly implement these as a link on the right of a page as a Feedback icon.

Should also include flagging as Spam.

**Comment by jag3773** [comment]
Note: Issue #244 must be consulted before started on this.
