### ISSUE TITLE
OBS Setup Message Issue

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#230]
See attached screenshot, the messages during OBS setup are not correct, though the pages were actually setup.  The skipping messages should go away.
![obs-setup-issue](https://cloud.githubusercontent.com/assets/107731/9854255/1db37a94-5ac5-11e5-93b3-71c1298a21b3.png)

**Comment by phillip-hopper** [comment]
@jag3773 Those messages will not be displayed on the production server, only on the test server.

**Comment by jag3773** [comment]
That image is from the production server.

**Comment by phillip-hopper** [comment]
@jag3773 Well, that's a problem. I'll see what I can do about it.
