### ISSUE TITLE
Direct Link for OBS Export Plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#233]
We need a direct link to point people at the OBS export script.  Currently you have to navigate to en/obs/ and then click on the Get Template button.  We need a link that will take someone directly to the Get Template modal window.

**Comment by phillip-hopper** [comment]
@jag3773, In order for that to work, the toolbar button will need to be visible all the time, not just on OBS pages.  Is that by itself enough to resolve this issue?

**Comment by jag3773** [comment]
No, I need a URL that I can link to, so that it is easy to send people directly to the correct place.

**Comment by jag3773** [comment]
@phillip-hopper I don't think #250 fixes this.  We still have the same scenario where we have to point people to a page and then they have to click something to actually get to the export, unless you are thinking that we have some way to automatically load that JS snippet?

**Comment by phillip-hopper** [comment]
@jag3773 Any link to Door43 that runs that javascript function will do the trick. It could be in the sidebar, or in document.load();. Perhaps it would help to be extremely specific in describing what you are looking for.

**Comment by jag3773** [comment]
I tried to be as specific as possible, OP: "We need a link that will take someone directly to the Get Template modal window."

I need 1 link that I can pass out that takes someone directly to the download OBS template feature.  For example, https://door43.org/en/obs#get-template .

Does that make sense?

**Comment by phillip-hopper** [comment]
@jag3773 Yes, it does now. You want an external link, not a link from within door43.org.  Try this link: http://test.door43.org/link-test

**Comment by jag3773** [comment]
OK, that should work.  Can we put that on any page then?

**Comment by phillip-hopper** [comment]
@jag3773 Yes, and you will need to enable embedded html in order for the pop-up to open automatically when the page loads.
![image](https://cloud.githubusercontent.com/assets/5262964/10008713/03deb058-60a0-11e5-8b26-bc7698f65cd0.png)
