### ISSUE TITLE
Merge tools ?

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#247]
I'm wondering if we should merge the unfoldingWord-dev/tools repository into this one.

There is a ton of overlap in the tasks to be done and I think it would be easier to keep track of everything on the code and issue side if it was all in one repo.

Thoughts @richmahn @phillip-hopper @alerque ?

**Comment by alerque** [comment]
No way. This repo has the backend for the website, largely in PHP and is deployed to web servers. The tools repo has scripts and tools that are mostly run from the command line, cron jobs, developer machines or eventually can be wired up to API callbacks. The deployment environment for this code is quite different. They should not be in the same repo. If anything there are a few bits ending up in this repo that should not be here: things that are not part of the Docuwiki instance and are actually scripts that are not web-facing. Those should be factored out into a different repo.

Keeping separation of concerns like this takes a little bit more care now but will save you a lot of headaches down the road as deployment environments change, development cycles differ, etc.

What you do with issues is another matter. You could conceivably run one issue tracker and just have devs figure out what code was affected for each task or issue, but I tend to think that split between web facing stuff on the website and backend wiring is one that will be helpful to have in the issue list as well.

In any event overlap in tasks to be done does not equate to merging repos for code that runs in completely disparate environments.

Somewhere (Slack?) we had a discussion about how the Door43 repo was being used, whether as a fork of Docuwiki or an installation/instance of it with modifications for a specific use case. We pretty much decided it was the latter (although it still has a little bit of multiple personality disorder showing through). But _either way_ the Docuwiki code that runs on a web server has no business being crammed into the same repo as a bunch of LaTeX, ConTeXt, Pandoc, Shell and other scripting that runs in any dev's terminal.

**Comment by jag3773** [comment]
Good comments @alerque .  I'm going to merge all the issues from tools into Door43, but we'll keep the code separate.  There is enough overlap with developers and feature set that it will be easier for us to manage work if we can look at both of these together.  I've also found a fair bit of duplicated issues between the two, so it should reduce dups as well.  Thanks!

**Comment by alerque** [comment]
@jag3773 Is there any way you can leave the old issue tracked feature enabled so that links aren't broken? All the cross references in commit messages to issues are currently dead ends. If the issue tracker was enabled but all the issues were closed they would show up with cross-links to the new issue location (the copied from link will mean they all have forward references). That way one can find their way from the commit log to the related issues and discussion.

**Comment by jag3773** [comment]
@alerque done.
