### ISSUE TITLE
Git Merge Error

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#254]
Error, as seen in attached screenshot:
![screenshot from 2015-09-22 09 18 48](https://cloud.githubusercontent.com/assets/107731/10022634/1f2799cc-610b-11e5-8dcb-93d6de879397.png)
`Warning: Invalid argument supplied for foreach() in /var/www/vhosts/door43.org/httpdocs/lib/plugins/door43gitmerge/action.php on line 757`

**Comment by richmahn** [comment]
@jag3773: @neutrinog hasn't responded 
![screenshot](https://cloud.githubusercontent.com/assets/2839925/10025326/edccf1de-6118-11e5-99fe-b999ecc6f42e.png)
to me on Slack about this. Looks like it is trying to go through two foreach loops with a variable called $user_array which was just added in the last commit. I don't see it being assigned a value anywhere. I put if-thens around them for that variable to have been set and be an array, so it got past that error, but now it just shows English text and the drop downs have no options. https://door43.org/aad/obs/01?do=door43gitmerge

Waiting to hear from Joel about it.

**Comment by da1nerd** [comment]
@kbuildsyourdotcom can you take a look at this?
