### ISSUE TITLE
Index Review

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#256]
@superdav42 Now that we are upgraded to the latest DW, do we still need to be using the enhancedindexer?  Can we go back to the regular index?

We are often getting errors from the enhancedindexer cron and I'm wondering f it's necessary to keep doing it this way.  Perhaps we can stop running the manual indexing entirely?

**Comment by superdav42** [comment]
@jag3773 I don't see any mention of the indexer in any of the release notes so I think we'd have the same problems with the index being out of date if we disabled the cron. It is often the case to run indexing job like this in many software projects I've worked on. The hook to trigger an index on a page load seams really like a hack and is just included because not everyone can use cron jobs. The enhancedindexer is 10x faster than the regular indexer which just wasn't keeping up.

What errors are you getting?

**Comment by jag3773** [comment]
The cron is running `/bin/php -d memory_limit=1024M /var/www/vhosts/door43.org/httpdocs/lib/plugins/enhancedindexer/bin/indexer.php -n en -r 1000 >/dev/null 2>&1 || /bin/php -d memory_limit=1024M /var/www/vhosts/door43.org/httpdocs/lib/plugins/enhancedindexer/bin/indexer.php -n en -r 1000 >/dev/null`

And bad output is either the simple:

```
E: Max runs reached 1000, restarting
E: Max runs reached 1000, restarting
E: Max runs reached 1000, restarting
```

Or the more disconcerting:

```
rom github.com:Door43/d43-en
 * branch            master     -> FETCH_HEAD
Everything up-to-date
From github.com:Door43/d43-en
 * branch            master     -> FETCH_HEAD
To git@github.com:Door43/d43-en.git
   09019bf..b95e242  master -> master
From github.com:Door43/d43-en
 * branch            master     -> FETCH_HEAD
To git@github.com:Door43/d43-en.git
   0a52502..3165471  master -> master
From github.com:Door43/d43-en
 * branch            master     -> FETCH_HEAD
To git@github.com:Door43/d43-en.git
 ! [remote rejected] master -> master (failed to lock)
error: failed to push some refs to 'git@github.com:Door43/d43-en.git'
fatal: Unable to create '/var/www/vhosts/door43.org/httpdocs/data/gitrepo/pages/en/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
fatal: Unable to create '/var/www/vhosts/door43.org/httpdocs/data/gitrepo/pages/en/.git/index.lock': File exists.
```

Maybe we just need an entry in .gitignore or something?
