### ISSUE TITLE
Redesign main page of Door43.org

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#26]
Ben is going to write 2 intro paragraphs that we will have translated into the GLs.

**Comment by superdav42** [comment]
For detecting preferred language the `Accept-Language` header looks like the most reliable solution. 

PHP 5.3 has built in support for reading the header with:

``` php
$locale = Locale::acceptFromHttp($_SERVER['HTTP_ACCEPT_LANGUAGE']);
```

see http://php.net/manual/en/locale.acceptfromhttp.php

I think twitter.com does a good job of using it. It's switches the language of the homepage based on the contents of the header. Which can be set in chrome with chrome://settings/languages. The user can switch languages at the top and this is stored in a cookie.

**Comment by jag3773** [comment]
Relates to #273
