### ISSUE TITLE
RTL PDFs have screwed up BIDI reversals

### ISSUE THREAD

**Issue by alerque** [unfoldingWord-dev/Door43#262]
In the RTL versions of PDFs generated using ConTeXt (e.g. the Persian OBS), the BIDI (bidirectional) detection module is turned on but the actual detection is not working properly.
- Some characters are properly flipped, others are not. This, for example, is supposed to be a closing parenthesis around the URL not an opening parenthesis towards the Farsi script:
  
  ![selection_062](https://cloud.githubusercontent.com/assets/173595/10117111/cfda39cc-6454-11e5-938d-03fd2a91b90a.png)
- Some are located at the wrong end of a reversed segment. One of these is incorrectly flipped as above but also at the wrong end of the URL so both the opening and closing paren end up in the same place:
  
  ![selection_063](https://cloud.githubusercontent.com/assets/173595/10117117/eb6aa474-6454-11e5-932e-3a9088062bca.png)
- Some direction switches are made where none should exist causing unnatural line breaks. There should have been room for "Share Alike" to stay on the same line here, I think the break is introduced by a bogus direction switch:
  
  ![selection_064](https://cloud.githubusercontent.com/assets/173595/10117121/0f51f626-6455-11e5-920e-472c316f9fed.png)

**Comment by alerque** [comment]
This is related to #261 in that the hyperef package also has issues understanding what's going on at BIDI level boundaries.

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/door43.org #115](https://github.com/unfoldingWord-dev/door43.org/issues/115) via [**ZenHub**](https://www.zenhub.com/)
