### ISSUE TITLE
New Projects in uW Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#277]
_From @jag3773 on July 29, 2015 20:3_

We need to provide access in our catalog to many of these 'newer' projects as standalone projects (tA, tN, tW, etc.).  In particular, PDFs should be available.  Related to #112 

_Copied from original issue: unfoldingWord-dev/tools#113_

**Comment by alerque** [comment]
Related to link should now be unfoldingWord-dev/Door43#278.

**Comment by jag3773** [comment]
Superseded by https://github.com/unfoldingWord-dev/translationDatabaseWeb/issues/256 and related issues.
