### ISSUE TITLE
Handle PDFs better in uW Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#278]
_From @jag3773 on July 29, 2015 20:1_

We need to revisit how we are handling PDFs in the uW catalog and figure out the best way to provide programmatic access to them.

_Copied from original issue: unfoldingWord-dev/tools#112_

**Comment by alerque** [comment]
Translated into plain geek speak: you need an API that's actually an application programming interface.

**Comment by jag3773** [comment]
This falls under a larger tD issue: unfoldingWord-dev/translationDatabaseWeb#221.
