### ISSUE TITLE
Include Page number in term link

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#283]
_From @jag3773 on July 22, 2015 19:43_

Currently, the PDF links to key terms, which is ideal for computer use.  However, we plan to print some of these as well, so it would be great if we could include the page number that the term shows up on in addition to the link.

_Copied from original issue: unfoldingWord-dev/tools#105_

**Comment by jag3773** [comment]
_From @richmahn on July 24, 2015 0:50_

Should be possible since it links to the page. Will have to learn how to know what page it links to and print it. However, this all comes from the HTML file when generated by pandoc to a PDF, so may be difficult.

**Comment by alerque** [comment]
This issue doesn't specify what PDF's are involved. If this is just the tN builds it will likely be easier to fix now that we are using a different LaTeX class and can customize the way pandoc fills in the template. If this involves other things we may need to look at getting them all "on the same page" [template] to save our sanity when messing with the hyperref package.
