### ISSUE TITLE
Fix API Logging Script

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#285]
_From @jag3773 on July 20, 2015 15:12_

The logging is not working.

_Copied from original issue: unfoldingWord-dev/tools#102_

**Comment by jag3773** [comment]
_From @phillip-hopper on July 20, 2015 17:58_

@jag3773, I'm not sure which script this issue is referring to.

**Comment by jag3773** [comment]
https://github.com/unfoldingWord-dev/tools/blob/master/uw/log_to_ga.py

**Comment by jag3773** [comment]
_From @phillip-hopper on July 22, 2015 15:37_

@jag3773, it seems that it isn't writing to the log because it isn't running. It wrote when I started it from the command line. However, it seems when it does run, the script is failing for a reason I haven't found yet.

**Comment by jag3773** [comment]
_From @phillip-hopper on August 17, 2015 11:53_

@jag3773: Is this still a problem?

**Comment by jag3773** [comment]
Yes, the data I see is 1 hit every few days, which cannot be correct.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by phillip-hopper** [comment]
I think we basically need to find a better way to do this than what we currently have.

**Comment by jag3773** [comment]
Outmoded by https://github.com/unfoldingWord-dev/uw-api.
