### ISSUE TITLE
Layout images in OBS PDFs to page grid

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#289]
_From @alerque on July 15, 2015 14:56_

As is typical with Bible printings where typesetting must be done on a vertical grid to avoid bleed-through on thin paper making lines hard to read, so the images in the 2up PDF output should be lined up between front and back pages (or in this case all the way through the document). The images being offset one way or another produces some pretty serious bleed through when printed on cheap paper.

_Copied from original issue: unfoldingWord-dev/tools#88_

**Comment by alerque** [comment]
You can go ahead and assign this one to me. It will be a while before it's actually done, but I already started playing with code so if anybody else is going to work on it they should at least ping me first and see what the status is.
