### ISSUE TITLE
Language properties not set

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#290]
_From @alerque on July 15, 2015 14:52_

The OBS - PDF output (even after the stuff in #86 gets merged) does not tag the content so that ConTeXt actually knows what it's typesetting. As a result it ends up doing some things wrong. One example is that hyphenation is being done based on English language rules, but in, for example, Turkish, that breaks words on the wrong boundaries.

This will also be an even bigger problem for accessibility tools like screen readers as the output isn't tagged right and also for complex script languages that need more clues about where to typeset content that just starting at the top left.

The correct per-language packages and settings need to be loaded and the body content correctly tagged (possibly differently than the front/back matter).

_Copied from original issue: unfoldingWord-dev/tools#87_

**Comment by alerque** [comment]
This got partially fixed incidental to adding RTL support in unfoldingWord-dev/tools#127. The body language was tagged in [11fbeaf](https://github.com/alerque/uw-tools/commit/11fbeaffa9d6b1f8501a675f657674839f770a5d) and some lang specific typesetting issues come free with the tweaks in [585b5fd](https://github.com/alerque/uw-tools/commit/585b5fd3c4baea0f8f7f3e4ffe708dfb799f0e5f). However there are still a few places this needs to be addressed.
