### ISSUE TITLE
Check for fields that may be missing (tD)

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#3]

**Comment by richmahn** [comment]
I could use more info on this one, @leok22 . Is this connectivity/data-sharing between door43.org and td.unfoldingword.org?

**Comment by jag3773** [comment]
This is a review of the current database layout and a conception check to
verify that we are tracking all of the information we should be.  Another
way to put this would be, "What other information do we need to track?"

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by jag3773** [comment]
This is for tD and should be in unfoldingWord-dev/translationDatabaseWeb.
