### ISSUE TITLE
Private Email Plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#339]
If we could get a chat plugin setup that allows users to direct message one another that would save a lot of administrative overhead of trying to connect people together without sharing user's email addresses.

Something like https://www.dokuwiki.org/plugin:simplechat may have promise, but that is very old.  Can we find something newer that provides the direct message functionality?  Note that the primary use here is not a live chat so much as a private email system where individual's personal information isn't shared.

Use case is allowing translators and coordinators to connect with other people who are working in the same language.

**Comment by phillip-hopper** [comment]
This may be helpful: http://jqueryhouse.com/jquery-chat-plugins/
