### ISSUE TITLE
ODT page tools icons not aligned correctly with RTL language

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/Door43#354]
When a right-to-left language is selected, the page tools icons for the ODT plugin are not aligned correctly when hovering.  See [this file](https://github.com/unfoldingWord-dev/Door43/blob/development/lib/plugins/door43obsdocupload/style.less) for a possible fix.

![image](https://cloud.githubusercontent.com/assets/5262964/10648391/1b90f9c6-780c-11e5-8b68-093e28b5d138.png)

**Comment by a-gundy** [comment]
Looks like the Export to PDF page tool icon also has this issue. Once the bookcreator plugin is in production it will need to adjust for this as well.

**Comment by a-gundy** [comment]
My PR to odt was accepted, so hopefully we'll see that change soon. Waiting on two other PRs (https://github.com/a-gundy/dokuwiki-plugin-bookcreator.git and https://github.com/a-gundy/dokuwiki-plugin-dw2pdf.git.
