### ISSUE TITLE
OBS Copy Plugin Links

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#356]
The OBS copy plugin is missing the step of adding links for tN, tQ, tW to the languages that get setup.

The [lang]/home and [lang]/sidebar pages need to be updated with the links for whatever was setup, for instance:

```
  * **[[:ru:obs:notes|Open Bible Stories tN (ru)]]**
  * **[[:ru:obs:notes:questions:home|Open Bible Stories tQ (ru)]]**
  * **[[:ru:obe:home|Open Bible Stories tW (ru)]]**
```

These should show up under the already coded entry for OBS `* **[[:ru:obs|Open Bible Stories (ru)]]**`.  You can check https://door43.org/tr/home for an example of what it should look like.

**Comment by phillip-hopper** [comment]
@jag3773 Does this issue still need fixed?

**Comment by jag3773** [comment]
Nope, should no longer be an issue in Gogs.
