### ISSUE TITLE
Undefined method error in UsfmTag plugin

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/Door43#368]
This is the error message:

```
Fatal error: Call to undefined method UsfmText::setBookName() in
  /var/www/vhosts/door43.org/httpdocs/lib/plugins/usfmtag/UsfmText.php on line 171
```

Unit tests need to be written that verify the bug exists and is fixed.

**Comment by richmahn** [comment]
Observation:

Happens only with the first chapter and first chunk of the chapter of any book. If you remove the \cl <name> tag from the ULB usfm text, it works. 

Somehow the \cl syntax is causing there to be no chapter number (\c) set in UsftTagDecoder for the UsfmText object.
