### ISSUE TITLE
Consolidate all noto-<lang>.tex files in obs/tex to one noto.tex file

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/Door43#376]
We need to make it so we don't need a new noto-<lang>.tex file in the tools/obs/tex dir for every non-Latin script language. It should be that we just need one noto.tex file (or fonts.tex file since we already have languages not using Noto fonts, i.e. "am").

It should be possible to put all font names and the UTF-8 character ranges in one file. We need to check that not all the font files get loaded in the generated PDF, but just the ones for the existing characters in the file, which I assume is how it will work.

Useful web pages for getting character ranges:

http://www.unicodemap.org/

http://www.ssec.wisc.edu/~tomw/java/unicode.html

**Comment by alerque** [comment]
I have some prior work on this. I tried a couple approaches and didn't like any of them, but maybe ping me in Slack or here before you actually sit down to fix this one.

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/door43.org #116](https://github.com/unfoldingWord-dev/door43.org/issues/116) via [**ZenHub**](https://www.zenhub.com/)
