### ISSUE TITLE
Import Strongs Greek

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#379]
We need to import the Strongs data for Greek from https://github.com/morphgnt/strongs-dictionary-xml.  This will show up as the tW for the Greek NT.

Possibly helpful: https://github.com/jag3773/strongs-xmltodokuwiki.

**Comment by klappy** [comment]
Moved to translationCore and superseded by UGL.
https://github.com/unfoldingWord-dev/translationCore/
