### ISSUE TITLE
Import Hebrew for tS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#381]
We need to import Hebrew from https://github.com/openscriptures/morphhb.

This process will entail:
- [ ] Convert text to USFM
- [ ] Import to API via tools/uwb/usfm_tS_import.py
- [ ] Import parsing information and work with @neutrinog to make this available in the app. See https://github.com/unfoldingWord-dev/ts-android/issues/1001.  Possibly helpful: https://github.com/jag3773/strongs-xmltodokuwiki.

**Comment by klappy** [comment]
moved to: https://github.com/unfoldingWord-dev/translationCore/issues/33
