### ISSUE TITLE
Import Strongs Hebrew

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#382]
We need to import Strongs data from https://github.com/openscriptures/HebrewLexicon.  This will show up as the tW for the Hebrew OT.

Possibly helpful: https://github.com/jag3773/strongs-xmltodokuwiki.

Note: it would be nice to import the BDB dictionary information as well, just not sure how all that will look atm.

**Comment by klappy** [comment]
Moved to https://github.com/unfoldingWord-dev/translationCore/issues/33
