### ISSUE TITLE
Fix Urdu PDF Issues

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#397]
At least the following issues need fixed:
- [x] Last frame of book seems to have it's text reversed with the reference
- [x] Text should be right aligned
- [x] Back matter "Share Freely" not spaced correctly
- [x] Should TOC be reversed?

**Comment by richmahn** [comment]
@jag3773 Right, need to make sure all text is correctly R-to-L as they expect it to be. Do we have someone we can specifically ask about this language?

Also, should numbers still be Left to Right for their digits? For example, the story # in the title is at the far right, but is still left-to-right with its digits, e.g. 43 is still 43. I assume that is correct, but just wanted to check.
