### ISSUE TITLE
Formatting problem with tags in TFT

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/Door43#400]
This issue is related to Help Desk ticket 1519:

Please see problems with formatting tags in Numbers 1:1-3.  P

We are seeing “anchor_label” tags in the TFT instead of verse markers - https://door43.org/en/bible/notes/num/01/01 

Also see: https://door43.org/en/bible/notes/2th/01/03 or https://door43.org/en/bible/notes/jer/07/08 for examples.

Same footnote problem exists in ULB and UDB:  https://door43.org/en/bible/notes/jhn/08/09

**Comment by jag3773** [comment]
@richmahn we need to get this fixed.  Seems like this should be a pretty easy change somewhere in the USFM Tag plugin.

**Comment by richmahn** [comment]
Fixed.
