### ISSUE TITLE
 Change Request for Formatting of Translation Question Pages 

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/Door43#403]
This issue relates to Help Desk Ticket 1586:

We made a formatting choice for the TQ pages at the very beginning. We put the period at the very end of the answers, after the Bible reference in square brackets. 

Hide quoted text
A. Beth Ezel mourned, for their protection was taken away [1:11].

We now regret that decision, for several reasons. If possible, we would like you to do a global search/replace in the “en:bible:questions:comprehension” NS to:
Remove all periods after a single right square bracket (skipping the links with double brackets)
Replace the space before all single left brackets with a period and space, unless it follows one of these:
Question mark
Exclamation mark
Period (stray)
Period and single-quote mark
Period and double-quote mark
Exclamation mark and single-quote mark
Exclamation mark and double-quote mark
Question mark and single-quote mark
Question mark and double-quote mark
There reason for most of the exceptions above is that we have been forced to put question marks or exclamations marks in some sentences before the reference, or inside final quotation marks. These would have to be left in place, but the final period after there reference removed.

Hide quoted text
A. Many said, “He has a demon and is insane. Why do you listen to him?” Others said, “These are not the statements of one possessed with a demon. Can a demon open the eyes of the blind?” [10:19-21].

Hide quoted text
A. God gives us the victory through our Lord Jesus Christ! [15:57].

Hide quoted text
A. Paul meant this: Each one of you says, “I am with Paul,” or “I am with Apollos,” or “I am with Cephas,” or “I am with Christ.” [1:12].

**Comment by ChrisJarka** [comment]
@destatez  Is this issue closed?

**Comment by lrsallee** [comment]
Yes, Dave Statezni fixed this.
