### ISSUE TITLE
Update Tag Searches

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#411]
Please fix the queries on these pages to be the full text regex search rather than relying on the index.  (list coming)
- [x] https://door43.org/en/ta/admin/chunknumbers
- [x] https://door43.org/en/bible/admin-reports/03-check-tntm
- [x] https://door43.org/en/bible/admin-reports/03-review-reviewer
- [x] https://door43.org/en/bible/team-info/training/quick-reference/quick-reference-notes#standard-notes-general
- [x] https://door43.org/en/bible/admin-reports/02-publish
- [x] https://door43.org/en/bible/admin-reports/02-review
- [x] https://door43.org/en/bible/admin-reports/02-check
- [x] https://door43.org/en/bible/admin-reports/obe-admin/obe-admin
- [x] https://door43.org/en/bible/admin-reports/obe-admin/obe-create 
- [x] https://door43.org/en/bible/admin-reports/03-larry-to-do
- [x] https://door43.org/en/bible/admin-reports/check-tags-notes
- [x] https://door43.org/en/bible/admin-reports/03-jim-to-do

**Comment by ChrisJarka** [comment]
https://door43.org/en/ta/admin/chunknumbers
https://door43.org/en/bible/admin-reports/03-check-tntm
https://door43.org/en/bible/admin-reports/03-review-reviewer

**Comment by ChrisJarka** [comment]
https://door43.org/en/bible/team-info/training/quick-reference/quick-reference-notes#standard-notes-general
https://door43.org/en/bible/admin-reports/02-publish
https://door43.org/en/bible/admin-reports/02-review
https://door43.org/en/bible/admin-reports/02-check
https://door43.org/en/bible/admin-reports/obe-admin/obe-admin
https://door43.org/en/bible/admin-reports/obe-admin/obe-create 
https://door43.org/en/bible/admin-reports/03-larry-to-do
https://door43.org/en/bible/admin-reports/check-tags-notes
https://door43.org/en/bible/admin-reports/03-jim-to-do

**Comment by ChrisJarka** [comment]
Each of these pages represent what is needed for each of the 66 books. Please replicate for each of the books. 
- [x] https://door43.org/en/bible/admin-reports/notes-team-admin/jer 
- [x] https://door43.org/en/bible/admin-reports/notes-review-admin/jer 
- [x] https://door43.org/en/bible/admin-reports/questions-comprehension/jer

**Comment by ChrisJarka** [comment]
Phil - this is the syntax for the table that was on the https://door43.org/en/ta/admin/chunknumbers page.
^  Draft  ^  Check  ^  Review  ^  Publish  |
|{{pagequery>@en:bible:notes {{tag>[^}]_draft[^}]_}}; showcount; fulltextregex; sort=title:asc; display={title}; natsort; layout=table;hidemsg;hidejump;fontsize=80%}} |{{pagequery>@en:bible:notes {{tag>[^}]_check[^}]_}}; showcount; fulltextregex; sort=title:asc; display={title}; natsort; layout=table;hidemsg;hidejump;fontsize=80%}} |{{pagequery>@en:bible:notes ^en:bible:notes:checking {{tag>[^}]_review[^}]_}}; fulltextregex; sort=title:asc; display={title}; natsort;showcount; layout=table;hidemsg;hidejump;fontsize=80%}} |{{pagequery>@en:bible:notes ^en:bible:notes:checking {{tag>[^}]_publish[^}]_}}; fulltextregex; sort=title:asc; display={title}; natsort;showcount; layout=table;hidemsg;hidejump;fontsize=80%}} |

I hope this helps. If so, then I will be glad to do this for the other pages also.

**Comment by ChrisJarka** [comment]
Backlinks are not working either.
See https://door43.org/en/ta/vol1/translate/translate_names where there should be links from https://door43.org/en/bible/notes/ezr/01/01 or https://door43.org/en/bible/notes/ezr/01/07 as well as tons of other Bible chunks.

![image](https://cloud.githubusercontent.com/assets/5262964/11877682/d98d8758-a4be-11e5-974d-6adc4114596e.png)

**Comment by ChrisJarka** [comment]
All of the OBE pages are not showing the Bible References information. The old syntax is:
 ===== Bible References: =====
{{topic>:en:bible?aaron&nocomments}}

See: https://door43.org/en/obe/other/aaron for example

**Comment by ChrisJarka** [comment]
Wondering what is the progress of getting the backlinks to work on all the D43 pages to work.
Wondering what is the progress of getting the Bible References on the OBE pages to work.

**Comment by phillip-hopper** [comment]
I'm closing this because the original issue is solved.  There are other issues for problems brought up in later comments
