### ISSUE TITLE
Take the extractor out of the chronjob and into Jenkins

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/Door43#418]
## User Story

As a translation manager, I would like the refresh of data to happen more frequently during the business day in order to see data no older than 4 hours.
## Definition of Done

Refreshes should be scheduled to have approximately 3 times a day. (recommended at 6am, 12pm, and 4pm)
- [ ] Move Job into Jenkins
- [ ]  Schedule Jobs
- [ ] Work with Tom to adjust import and timing

**Comment by PurpleGuitar** [comment]
Test runs are complete -- data looks good.

**Comment by PurpleGuitar** [comment]
Finished and running in production.
