### ISSUE TITLE
Web interface for audio uploads (in progress)

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#44]

**Comment by phillip-hopper** [comment]
The repo is here: https://github.com/unfoldingWord-dev/dokuwiki-plugin-obs-audio-upload

The [translation plugin](https://github.com/door43/dokuwiki-plugin-translation) and [Door43Shared plugin](https://github.com/unfoldingWord-dev/dokuwiki-plugin-shared) are requirements for the audio upload plugin.

You can see this one in action here: http://test.door43.org/obs-vrs
