### ISSUE TITLE
Request to Fix Bible References search

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/Door43#445]
This issue rellates to Help Desk ticket 1668:

The tag search that Bible References section of the KT pages uses no longer works. Please update all OBE pages to new search code.

We are currently updating linked references, which is very when the internal page search is broken.

**Comment by jag3773** [comment]
Relates to #411

**Comment by jag3773** [comment]
For example, there is a "Bible References" section on https://door43.org/en/obe/other/aaron which should be pulling in a list of references that have "aaron" in them.  However, since the index is broke so is this list function.

**Comment by phillip-hopper** [comment]
The enhanced indexer has been updated and this appears to be working now.
