### ISSUE TITLE
Check for \p after \s5

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#448]
The ULB and UDB need to be checked to verify that \p occurs after every \s5.  If any are missing then the \p needs to be added.

These should be made as pull requests against https://github.com/unfoldingWord/ulb-en and https://github.com/unfoldingWord/udb-en.

**Comment by destatez** [comment]
Is there a link to the BNF for the usfm files? My specific question is whether the \p must follow immediately after the \s5.  There is at least one case where there is a \c line between the \s5 and the \p. 
As a point of reference, I am only finding \s5 in Luke 1 - Luke 4 in both ULB & UDB. Is my grep command not working correctly?

**Comment by destatez** [comment]
I found a link and downloaded usfmReference2_4, and although it gives syntax for each marker, it does not deal with ordering of markers. Are there some Door43 rules for this?

**Comment by lrsallee** [comment]
Jesse, is there a technical reason for this? Our chunks are so short--sometimes a single verse--that we don't really want these to all be paragraphs unless there is a major tech reason that we can't have several chunks formatted as a single paragraph.

**Comment by jag3773** [comment]
Note that this issue will be resolved when we switch to `\zChunk` markers instead of `\s5`.  In light of that I'll close this issue.
