### ISSUE TITLE
Remove \q Markers in UDB

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#449]
The \q markers need to be removed from the UDB.  Note well, we are talking about the UDB, the **dynamic** version.

Please remove them from the book of Joel first and make a pull request against https://github.com/unfoldingWord/udb-en.  Have Jim review.

If he is happy with the changes then we should run the script on the whole OT.  This should result in another PR that can be reviewed and merged when we get Jim's approval.

**Comment by destatez** [comment]
Jesse

I'm a little confused. I thought, from earlier discussions, that the repository was populated from etherpad, which is the "root" source of the data. The implications from your comments is that the repository is the "root" and if the text mods are pushed back up, they will then get populated into etherpad. Can you clarify this for me?

**Comment by destatez** [comment]
A further concern is that I just compared the pulled repository file \ulb\v2\1sa\031.usfm.txt with the latest version in etherpad and the Door43 htm associated page and they do not align, particularly for verse 12, which was update 2/10/2016. The repository seems to have a very "antique" version of that verse. (I know that this ULB verse has nothing to do with this issue, but it evidences my concern)

**Comment by ChrisJarka** [comment]
Should this issue be closed and moved to https://github.com/Door43/udb-en/issues?

**Comment by jag3773** [comment]
This issue was moved to Door43/udb-en#113
