### ISSUE TITLE
Wording in tA Manual pages

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/Door43#453]
In the tA Manual pages there are two phrases that are automatically generated when pulling information form the YAML into the page.
Line 1 now states - This module answers the question: [then the information after "question:" on line 3 of the YAML]
Line 2 now states - Before you start this module have you learned about:  [then a bullet list of slugs listed after 'dependencies:' on line 7 of the YAML.]

Is it possible to have "This module answers the question:" in bold?
Additionally, we would like know if we can suggest a change to the wording of Line 2.

**Comment by phillip-hopper** [comment]
@jag3773 or @benjore: These phrases are now pulled from https://door43.org/tl/ta/vol1/intro/ta_intro instead of being hard-coded, so a developer isn't needed to change the wording. But someone needs to make the decision on if the wording should be changed, and what it should be changed to.
