### ISSUE TITLE
Add Cron for removing Link Names for tW and tA-Topic Links in Notes

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#454]
Some code to do part of this at https://github.com/unfoldingWord-dev/tools/blob/master/general_tools/dokuwiki/simplescripts.sh#L19.

Note that this should be confined to the notes namespace.

The script to run should probably end up in the tools repo, cron should be setup in puppet and configured to run the script each night.

**Comment by ChrisJarka** [comment]
https://door43.org/en/ta/vol2/translate/figs_grammar is an example how the 'recommended' has the pipe and text
https://door43.org/en/bible/notes/gen/21/12 has 2 examples in the tN of tA links with the pipe

NOTE: *_only *_the links for tA should have the pipe and text removed. The biblical reference links in the tN should not be affected (no pipe and text removed).

**Comment by lrsallee** [comment]
We create TW and TA links in the D43 notes without the pipe or link title. We want the title to be pulled from the target page. So an TW link would be:

[[:en:obe:other:johnthebaptist]]

We have found that when switching between D43 editors, D43 often inserts the title into the link. The above link would become:

[[:en:obe:other:johnthebaptist|John (the Baptist)]]

This is all well and good until we change the title on a target page, or translate the target page into another language. Either of these changes will not cause the link to update--it will continue to display the old title. 

We would like a script to clean out the titles so we can see if they point to the proper pages. It is also going to be necessary to clean them out before the linked pages are translated in to GL's. 

Please do **not** clean out the Bible reference links in the notes, such as:

[[:en:bible/notes/luk:19:13|19:13]]

Please confine script to links with targets in the en/obe and en/ta namespaces.

**Comment by destatez** [comment]
Jesse. There is still an issue here. I did a global removal of all ta & obe pipes and links last week. Someone brought to my attention that these ought to be removed??  I have searched the Notes again and find the same instances that I removed. Can you guys correct his, so that the links are not filled in for these particular types of references?

**Comment by richmahn** [comment]
I have made a script that should run ever night that ONLY removes the Title to the right of the pipe (|) for tW's (:kt: and :other:) and tA pages (:ta:).

**Comment by destatez** [comment]
There is still an issue here. I created a new page, Word Links, that will exist for every book. I just did 1co for starters. The file was created without any pipe symbol, and thus nothing to the right. d43-en/bible/notes/1co/00/words.txt, commit on 3/24. I then did a manual, web-page edit of that file and when it was saved, the pipes appeared, as well as the text to the right: https://door43.org/en/bible/notes/1co/00/words - 2016-03-28 14:21 revision. I did not manually put in the pipes for the 250+ entries. (I did do a follow-on edit to add to the piped value, but that was just an experiment to check on format) What tool is adding and expanding the pipes for the link?

**Comment by richmahn** [comment]
@destatez Currently we only remove the link names from files that are numbers, such as 00.txt, 01.txt. You can see this in the simple script I made: https://github.com/unfoldingWord-dev/tools/blob/master/general_tools/dokuwiki/clean_bible_notes_pages.sh

I'm not sure what is putting the pipes into the text though, but my script is only set for chunk note pages. Should we be scanning ALL pages made in the bible/notes namespace?

**Comment by destatez** [comment]
These pages, words.txt and tatopics.txt were requested by Chris J. There will be a set for every book. I am talking with Chris K related to this, to see if he can develop a script to dynamically create the content of these. For now I have a PC-based script that generates them, only 1co for starters, but which I was planning on running that script regularly for every book and pushing those up to GitHub.

**Comment by destatez** [comment]
@richmahn @ChrisJarka @klappy  I would believe that we want to open up the file-set for your script to cover more than the numbered files
