### ISSUE TITLE
Formatting requests for Bible tN PDFs

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/Door43#474]
@richmahn 
- [x]  tW in the TOC are alphabetized by first OBS and then Bible only words. Please combine the list so that it is a continuous alphabetical list.
- [x] each of the tQ pages (chapter) listed in TOC
- [x] each of the tA topics/pages listed in the TOC
- [x] Have the Title Page bookmarked
- [x] Have the TOC bookmarked
- [x] Remove the second bookmark for the License and Copyright
- [ ] Format the chapter numbers (in ULB and UDB) so that they stand out. Either larger, offset, or drop cap.
- [x] Format the verse numbers (in ULB and UDB) so that they are superscript and/or lighter
- [ ] Underlining in tA topics are not rendering correctly - they are showing as italicized.  See Galatians - the bottom of page 323 - "he watched over me" and the top of the next page where it states that the idiom is underlined.
- [x] Format the tQ pages like the tQ documents. Lines between set of Q and A. Bolded Q? and A.
- [ ]  Format scripture quotes to match the website - a vertical bar to the left of the block quote.

**Comment by richmahn** [comment]
@ChrisJarka For the tA topics not rendering correctly, this is a bit trickier, as I simply take a URL like https://door43.org/en/ta/vol1/translate/figs_idiom and get just the rendered HTML from Dokuwiki like so: https://door43.org/_export/xhtmlbody/en/ta/vol1/translate/figs_idiom . The latter link has it italicized, the former underlined...not sure why. I think this is part of Dokuwiki...will have to investigate.

**Comment by ChrisJarka** [comment]
We need to know if the underlining won't render correctly. Since, the page refers to the underlined words/phrases in the explanations.

**Comment by richmahn** [comment]
@ChrisJarka I was able to fix the underline by adding in-line CSS styling to that element (the second link I gave in my above comment has no CSS style sheet since it is raw HTML). Are there any other noticeable differences between the PDF and the Dokuwiki view page of a given wiki page?

**Comment by ChrisJarka** [comment]
@richmahn I'm working on the pages - wiki, gogs and pdf this weekend. I should know better by Monday evening.

**Comment by richmahn** [comment]
@ChrisJarka Unfortunately, even thought I got it showing underlined text in that second link (_export/xhtmlbody/...) it still doesn't render in the PDF...underlines are a pain. Even Markdown doesn't support underline (we have to put HTML to make it underline in Gogs)

**Comment by richmahn** [comment]
@ChrisJarka Still have two issues to deal with, or to get your feedback on. For chapter numbers in ULB and UDB text, where do we even show those? There is the title of the tN section that has the chapter, but I never see anything in the chunk text.

Second, the more I read about underlining in typesetting, it sounds like it is discouraged and that emphasis (italics) is what is preferred. See https://groups.google.com/forum/#!msg/pandoc-discuss/I8bU3O9dc8s/QcnBr9_VhaoJ for the discussion on why Pandoc, which we use to generate the PDF, doesn't even acknowledge the use of &lt;u&gt; for underlining, for "underline 
is an antiquated way to do emphasis". Do we need this? If not, I know sometimes form examples have underlines. We will need to make sure they use _ (underscore) and not a underlined blank space.

**Comment by richmahn** [comment]
@jag3773 What do you know about underline being discouraged in typesetting/PDFs? (see comment above). Should we support it?

**Comment by ChrisJarka** [comment]
@richmahn If underlining is not available - then we will need to rewrite our instructions. 
Also, I thought that italics was not used in some languages but underlining was. 

Do you or @jag3773 have any ideas on the formatting that we can use (other than bold) to point out words in a sentence that we want the learner to quickly see.

**Comment by ChrisJarka** [comment]
@richmahn this is what the chapter looks like in the ULB on the wiki.
![chapter number in ulb](https://cloud.githubusercontent.com/assets/9850185/15889985/6c4babc4-2d3b-11e6-89cd-d7e034eaccc1.png)
this is what the chapter looks like in the ULB on the pdf
![chapter number in pdf](https://cloud.githubusercontent.com/assets/9850185/15890038/b2d21a92-2d3b-11e6-93e6-3a2808a01643.png)

I see that the chapters in tS do not show on the chunks.

**Comment by richmahn** [comment]
@ChrisJarka Oops, you're right. I was using Jude in all my experiments and UDB doesn't have a chapter number for it for some reason. ULB does.

**Comment by richmahn** [comment]
@ChrisJarka Good point about the italics in other languages, Chris. Even with Chinese it is hard to see italics, but underlining isn't so good either. While we do need to figure out if we need to find ways to have underlining, the other option is to **_bold AND italic**_ such words (**\* around the words) , to make them stand out a bit more but be different than bolded section titles.

**Comment by ChrisJarka** [comment]
@richmahn we noticed that the second bullet mark changes the smart quote to a backwards smart quote.
Can that setting be changed?
Also, can the second bullet be something other than a dash? Maybe something like an open dot or a square?

**Comment by richmahn** [comment]
@ChrisJarka Can you give me an example where this is happening?
