### ISSUE TITLE
change repo permissions

### ISSUE THREAD

**Issue by sea-liesch** [unfoldingWord-dev/Door43#481]
Now that jmorgan has resigned from WA, I need to be able to control his repos.   That is, rename, delete, etc.
Thank you,

~Chuck

**Comment by ChrisJarka** [comment]
@sea-liesch would you want them changed to door43/xxx repos?

They can be forked to your own repos. As for the other permissions - those could come from/ be done by @jag3773 I believe.

**Comment by sea-liesch** [comment]
I suppose I could fork them - but then those original repos become 
abandoned and unmanaged.   I think it would be wise that when people 
leave, if we  are able, to give somebody else guardianship of those repos.

I realize in the big picture that not everyone that uploads something to 
d43 is going to tell us when they are done.

~Chuck

**Comment by ChrisJarka** [comment]
No to mention the hundreds of 'junk' repos 'out there.'

**Comment by jag3773** [comment]
Please email me details @sea-liesch , this is the wrong place to discuss this.
