### ISSUE TITLE
Content review web app (in progress)

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#49]

**Comment by phillip-hopper** [comment]
This is the repo: https://github.com/unfoldingWord-dev/dokuwiki-plugin-obs-review

You can see the first part in action on the test server at http://test.door43.org/en/obs. The text across the top of the OBS pages that says, "This resource is published on unfoldingWord as checking level 3..." is coming from this plugin.

**Comment by jag3773** [comment]
Random note that I think is related: Plugin which adds a "Review this Content" button on any page that is published in our API. Thus, pt-br/obs/01 should have a button since it is published on api.unfoldingword.org.
