### ISSUE TITLE
Figure out how to sync changes with door43.org when the user is done

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#54]

**Comment by richmahn** [comment]
Is this what the gitcommit plugin is for, or something else?

**Comment by jag3773** [comment]
@leok22 do you know what the context is on this?

**Comment by leok22** [comment]
Nope, I just copy and pasted this from Basecamp @jag3773 @richmahn

**Comment by richmahn** [comment]
Yeah, I need to figure out what is needed to be copied over from BaseCamp from my list of issues. Does door43.org automatically sync changes after a user makes to a OBS story page with github? I would think so, but haven't tested it myself.

**Comment by jag3773** [comment]
closing since we don't know what this is about.
