### ISSUE TITLE
Current editor adds page name after links (the "|LinkName" bit). 

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#57]
This could be problematic for notes teams and such.  Switching editors causes this to happen.

**Comment by superdav42** [comment]
Not sure what the problem is. Having |LinkName is a good thing right?

**Comment by jag3773** [comment]
No, we want the display name to automatically pull in the title of the
respective page, which happens if a specific link name is not given.

**Comment by superdav42** [comment]
@jag3773 So you don't want users to be able to set the link name to anything other than the page name? Essentiall you want content such as [[:en:bible:home|Bible]] to be rewritten to [[:en:bible:home|]] on save?

**Comment by jag3773** [comment]
That is correct.
