### ISSUE TITLE
tA Copy Plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#59]
This plugin would be similar to the obs-setup plugin, but for translationAcademy.

**Comment by phillip-hopper** [comment]
@jag3773, I'm going to start by copying these directories:
- vol1
- vol2
- workbench

Is there anything else that needs to be included?

**Comment by phillip-hopper** [comment]
**To whomever works on this issue next:**

I already have part of this done. https://github.com/phillip-hopper/dokuwiki-plugin-door43ta

**Comment by jag3773** [comment]
Demo tA endpoint is at http://td-demo.unfoldingword.org/publishing/ta-en.json.

**Comment by phillip-hopper** [comment]
@jag3773: Can this be closed now?
