### ISSUE TITLE
Grep DokuWiki Plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#61]
We need a plugin that forks to grep and is 100% accurate every time.  Can you recreate the 'pagequery' plugin but have it fork to grep, forwarding the respective arguments.  As an example, to recreate what is on https://door43.org/en/bible/admin-reports/check-tags?do=edit&rev=0,  we can run `grep -re "{{tag>" * | grep -v -e "{{tag>create" -e "{{tag>delete" -e "{{tag>draft" -e "{{tag>check" -e "{{tag>review" -e "{{tag>text" -e "{{tag>discuss" -e "{{tag>publish"` while in the 'ns:en:bible:notes' directory.  The result is returned _way_ faster and is always accurate.

**Comment by superdav42** [comment]
@jag3773 ready to close this out?

**Comment by jag3773** [comment]
How can we document that this exists and how to use it?

**Comment by superdav42** [comment]
I added it to the pagequery cheat sheet that is found in a button at the top of the editor.
