### ISSUE TITLE
Exclude sub dir on Topic Search

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#63]
When using the topic plugin to create a query it would be nice to be able to exclude a sub namespace.

**Comment by jag3773** [comment]
Also for a pagequery search.

**Comment by jag3773** [comment]
@superdav42 Is this taken care of?

**Comment by jag3773** [comment]
@superdav42 Is this taken care of?

**Comment by superdav42** [comment]
@jag3773 Turns out it's already supported in pagequery like:

```
{{pagequery>@en:bible:notes:rom ^en:bible:notes:rom:01 \{\{tag>[^{]*publish[^{]*\}\}; fulltextregex; sort=title:asc; display={title}; natsort; showcount; layout=table;hidemsg;hidejump;fontsize=80%}} 
```

see https://www.dokuwiki.org/plugin:pagequery#complete_syntax_table
