### ISSUE TITLE
Track Number of Published Items

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#64]
The text team needs to get at least a weekly report of how many items have been published.  This should key off of the 'publish' tag and should break down by namespace.  Ideally, this would have a total number of pages with that tag on it and then be able to compare it to the past (at least a day, week, and month lookback).

**Comment by jag3773** [comment]
@PurpleGuitar Is this something that you are working on?

**Comment by PurpleGuitar** [comment]
@jag3773 Yes, this sounds like part of the work I'll be doing for CJ.

**Comment by jag3773** [comment]
Is this done now @PurpleGuitar ?

**Comment by PurpleGuitar** [comment]
Yes, pending user approval.
