### ISSUE TITLE
Dynamic API: Verse Search

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#68]
We need a dynamic API endpoint that returns Scripture.  Endpoint should accept verses or verse ranges as well as language and/or version requests.

**Comment by jag3773** [comment]
This should be processing content from the unfoldingWord API.  The catalog to process is https://api.unfoldingword.org/ts/txt/2/catalog.json.

Requests and responses should all be JSON.  Options to accept are at least:
- Language (using IETF language codes)
- Version slug (ulb or udb for English)
- Book name (also variant book names and abbreviated names (Romans, Rom, Rm).  This needs to be localizable, so that references can be given in any language in the world (for example, Romanos for Spanish).
- Verse or verse range (for example 8:1, or 8:2-9:15)

Once written this will be hosted on the api.unfoldingWord.org domain.

The code base for this issue and #69 should be the same, and we probably need a new Github repository for it.

Any other thoughts @richmahn ?

**Comment by Aarontse** [comment]
Please confirm if this is correct or not:  
1.The system should let the user to input parameter as listed as Options to accept are at least. with one extra: the need TEXT.
2.The system located the need files from the the catalog -> lang_catalog -> notes & source.
3.The system start to search for the needed TEXT in those files.
4.Feedback result when search completed.

IS there any doc on the definition of tag usage in the used JSON file?

**Comment by Aarontse** [comment]
Hi Jesse,

I have drop some comment on #68 and #69 in GifHub, did you got it OK?

Aaron

**Comment by richmahn** [comment]
@Aarontse Hi Aaron, I am the Tech Lead for Door43 and will be seeing you through this feature. I saw your comment from 3 days ago. I'll be looking this over tomorrow (I'm in USA, so evening here now) to make sure I understand your process correctly and what you are asking. Hope we can talk then.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/uwadmin#44
