### ISSUE TITLE
Dynamic API: Search

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#69]
We need a dynamic API that can return results based on keyword searches.

**Comment by jag3773** [comment]
Related to #68

**Comment by Aarontse** [comment]
Is there any example of the source to be search?
Where will the source store? in file or database? path for the source? 
And the sample calling (parameter need) for the API?

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/uwadmin#43
