### ISSUE TITLE
Spreadsheet to Track GL Progress

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#73]
We need to create a Google Spreadsheet that will be a stop gap solution for tracking translation progress across the GLs.

The rows should represent GLs, the columns represent content chunks.  For example:

| Language | tA vol1 | ta vol2 |
| --- | --- | --- |
| English | 90% | 50% |
| Spanish | 0% | 0% |

**Comment by leok22** [comment]
Is this what tD will eventually handle @jag3773 ?

**Comment by jag3773** [comment]
Yes.  Having it speced out in a spreadsheet will solve the immediate
problem and also provide a blueprint for the tD devs on what we need.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
