### ISSUE TITLE
Project List

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#76]
We need to make a canonical list of all our projects.  To include for each:
1. Developer skill sets for project
2. Code and Issue location
3. Our readiness to accept contributions for it
4. Help Wanted, or not
5. Who the team lead is.

Anything else?  Some information can be culled from https://door43.org/en/dev/teams.

**Comment by benjore** [comment]
Does this file accomplish this? https://docs.google.com/document/d/10sD2Trwc2wGPWgMgrgKg-vkBpXqJ2luu__ceFNetM2U/edit
