### ISSUE TITLE
Revision History Plugin Update

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#87]
We need to update the view of the revision history comparison page such that:
1. The whole page is shown when comparing 2 revisions
2. On the revision compare page, there is a drop down box on either side of the page that allows you to select an arbitrary revision to compare.

This is an example page that we are talking about modifying: https://door43.org/playground/tim?do=diff&rev2%5B0%5D=1435702880&rev2%5B1%5D=&difftype=sidebyside.

**Comment by superdav42** [comment]
FYI, the second part, adding a dropdown is already done in the latest version of dokuwiki, I'll see if I can backport it to our repo.

**Comment by superdav42** [comment]
@jag3773 done https://github.com/unfoldingWord-dev/Door43/pull/131
