### ISSUE TITLE
tA PDF Export

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#96]
Once unfoldingWord-dev/translationDatabaseWeb#68 is completed, we need a print ready and clickable PDF of tA.

Related to #104

**Comment by jag3773** [comment]
Rich, let's work with @phillip-hopper on this.  He is currently working on a DOCX export for tA.  Sometime we need to discuss which direction we want to go here and get started.

**Comment by jag3773** [comment]
Once unfoldingWord-dev/translationDatabaseWeb#68 is completed, we can officially start on this.  Desired formats for tA are:

* [ ] Clickable PDF
* [ ] Print ready PDF
* [ ] Standalone static HTML site/page
* [ ] Mobile app
* [ ] Available as resource in tS

Anything else @benjore ?

**Comment by jag3773** [comment]
Demo tA endpoint is at http://td-demo.unfoldingword.org/publishing/ta-en.json.

**Comment by richmahn** [comment]
Now downloadable at https://unfoldingword.org/academy

Script is at tools/ta/pdf_export.sh (using html_export.py and files in the tex directory)
